using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;

namespace PruebasScanner.Models
{
    class Correos
    {

        public List<string> listCorreosMarca = new List<string>
        {
            "letymej13@gmail.com",
            "gabriela.poncedeleon@axa.com.mx",
            "francely.vicens@redlineuw.com",
            "amir.loske@allianz.com.mx",
            "paola.nava@chubb.com",
            "astrid_uribe@swissre.com",
            "andy@safehub.io",
            "roberto_gomez@swissre.com",
            "jimena_reyes@swissre.com"
        };

        public Dictionary<string, string> mailTagsV2 = new Dictionary<string, string>
        {
            {"Eliabeth Torres García","Allianz" },
            {"Paola González","Fianzas Avanza" } ,
            {"Ana Julieta Tello","Sof imex" }
        };

        public Dictionary<string, string> mailTags = new Dictionary<string, string>
        {
            {"Damara Aridjis González","Agroasemex"},
            {"Karen Alejandra Romero Garfias","Agroasemex"},
            {"Vanessa Blanco Manzano","Agroasemex"},
            {"Gabriela Monroy","AIG"},
            {"Verónica Baltazar Chávez","AIG"},
            {"Alma Ximena Solis","Allianz"},
            {"Anabel Corchado","Allianz"},
            {"Jessica Rincón","Allianz"},
            {"Magdalena Lugo","Allianz"},
            {"Mayra Barrón Bolaños","Allianz"},
            {"Sandra Cabello","Allianz"},
            {"Sandra Xóchitl Rocha Orozco","Allianz"},
            {"Rosalba Andrade Cortés","Allianz "},
            {"Claudia González Mondragón ","Allianz "},
            {"Mónica Metinides","Ana Seguros"},
            {"Leticia Olvera","Grupo Amistad"},
            {"María Susana Buendía Arana","Ex Patria "},
            {"Laura Peimbert","Grupo Amistad"},
            {"Leticia López Escamilla","Grupo Amistad"},
            {"Lourdes del Razo","Grupo Amistad"},
            {"Linda Mandujano","Grupo Amistad"},
            {"Patricia Villarroel","Grupo Amistad"},
            {"Marisol Gasca","Ex AMIS"},
            {"Ana Keny Andrade","Atlas"},
            {"Nancy Avilés","Atlas"},
            {"Yolanda Salmerón","Atlas"},
            {"Jaqueline Huitrón","Atlas "},
            {"Christiany Díaz Rodríguez","AXA"},
            {"Elena Megchun Güereca","AXA"},
            {"Gladys Eddy Ordoñez","AXA"},
            {"Marcela Flores Hernández","AXA"},
            {"María Gabriela Cosío Salazar ","AXA"},
            {"Sorimar Rueda García","AXA"},
            {"Verónica Mac Kinney Jaime","AXA"},
            {"Beatriz García","BMS"},
            {"Patricia Martínez","Chubb"},
            {"Alcynoe Aguilar","Chubb "},
            {"Cynthia Bretón","Chubb "},
            {"Rosa Isela Cárdenas","Chubb "},
            {"Stefany Escalona","Chubb "},
            {"Lorena Bernal","CNSF"},
            {"Gabriela López","CNSF"},
            {"Briza Islas","El Asegurador"},
            {"Claudia Rojas","El Asegurador"},
            {"Anna Sánchez","Fianzas Avanza"},
            {"Ariadna Barrera","Fianzas Dorama"},
            {"Ana Lourdes Mojarro","Fianzas Dorama"},
            {"Verónica Ponce","Fianzas Dorama"},
            {"Elizabeth Hernández Nolasco ","General de Seguros"},
            {"Karen Melissa Claudio Ricardo ","General de Seguros"},
            {"Marisol Castro Badillo","General de Seguros"},
            {"Livia Tovar","GMX"},
            {"Lorena Galván","GMX"},
            {"Hilda Elizabeth García Martínez","GMX"},
            {"Diana Contreras","GMX"},
            {"Claudia Gabriela Sánchez Luna","GMX"},
            {"Mayra Soto Esparza","GNP"},
            {"Eulalia Sánchez Hernández","GNP"},
            {"Liliana Rodríguez","GNP"},
            {"Alejandra Castillo Cedillo","GNP"},
            {"Elvia Edith Cuenca Esquivel","GNP"},
            {"Alicia García Reza","GNP"},
            {"Leticia Erazo Salgado","Grupo Valore "},
            {"Sandra Medellín Herrera","Grupo Valore"},
            {"Ana Karen Palma Navarro          ","Inbursa"},
            {"Brenda Ivonne Castro Milan","Inbursa"},
            {"Sandra Gutiérrez Gutiérrez","Inbursa"},
            {"Sara Judith Cano Granados","Inbursa"},
            {"Ana Bertha Mora","KOT"},
            {"Alejandra Legorreta","Mapfre "},
            {"Cintia Díaz","Mapfre "},
            {"Diana Bravo","Mapfre "},
            {"Mariana Rodríguez","Münchener"},
            {"Yuriria Equihua","Münchener"},
            {"Vanessa Meraz","Odyssey"},
            {"Enriqueta Reyes ","Peña Verde"},
            {"Margarita Naranjo Uribe ","Peña Verde"},
            {"Nayeli Gonzalez de la Vega Hernández ","Peña Verde"},
            {"Damaris Díaz","Proeducacion Fundación"},
            {"Maricarmen Castillo","Quálitas"},
            {"Laura Galindo","Patria Re"},
            {"Lety Gutiérrez Hernández","Patria Re"},
            {"Marcela Esperanza Soriano Ramírez","Patria Re"},
            {"Andrea Flores Serna","Rainmaker "},
            {"Dany Sámano","Rainmaker "},
            {"Lolis Martínez","Rainmaker "},
            {"María Elena Guadarrama Escorza","RSK Placement"},
            {"Elizabeth Gutiérrez García","Banorte"},
            {"Gabriela García Espinosa","Banorte"},
            {"Ofelia Castro Alcauter","Banorte"},
            {"Silvia Rayón","Sura"},
            {"Ana Julieta Tello","Sofimex"},
            {"Berenice Cervantes","Som.us"},
            {"Jenny Maldonado","Som.us"},
            {"Rosalía Del Castillo","Som.us"},
            {"Martha Beltrán","Som.us"},
            {"Nayeli Cortés","Summa Re."},
            {"Neyla Mena","Summa Re."},
            {"Tanya Cantú","Swiss Re."},
            {"Patricia Warrener","TBS "},
            {"Aurora Mateos","Thona"},
            {"Patricia Hernández","Viajes Tadeo"},
            {"Viridiana Ramírez Romero","Zurich "},
            {"Olivia Sandoval","Ex Willis"},
            {"Francisco Martínez ","Som.us"},
            {"Juan Martínez","Som.us"},
            {"Rogelio Sáenz","Som.us"},
            {"Jorge Pozos","Som.us"},
            {"Alejandro Hernández","Som.us"},
            {"Jorge Flores","GMX"},
            {"Gabriel Sánchez","GMX"},
            {"Alejandro Serrano","TBS"},
            {"Jorge Jockens","TBS"},
            {"Genuario Rojas","El Asegurador"},
            {"Andrea Rojas","El Asegurador"},
            {"Gabriel Iñesta","BMS"},
            {"Rafael Picazo","Summa Re."},
            {"Claudia Aragón","Summa Re."},
            {"Yolanda Vázquez","Summa Re."},
            {"Francisco Martínez Cillero","Patria Re."},


        };

    public List<string> listCorreos = new List<string>
        {
            "felipe.mejia@3c.com.co",
            "jairo.mejia@3c.com.co",
            "jan@acipanama.com",
            "mae@acreinsurance.com",
            "aguevara@acreinsurance.com",
            "adiaz@acreinsurance.com",
            "cvergara@acreinsurance.com",
            "gestribi@acreinsurance.com",
            "hriquelme@acreinsurance.com",
            "mcarrillo@acreinsurance.com",
            "ssoberanes@acreinsurance.com",
            "deborah.agnew@agnew-intl.com",
            "isela.carrillo@agnew-intl.com",
            "agnew@agnew-intl.com",
            "sharon.martindell@agnew-intl.com",
            "eescobar@agroasemex.gob.mx ",
            "jvazquez@agroasemex.gob.mx",
            "mcalderon@agroasemex.gob.mx",
            "parredondo@agroasemex.gob.mx",
            "rdelarosa@agroasemex.gob.mx",
            "mterrazas@agroasemex.gob.mx",
            "jhgalvez@agroasemex.gob.mx",
            "katheleenabril.ortega@aig.com",
            "alfredo.godinez@aig.com",
            "andrea.sanchez@aig.com",
            "andreseduardo.navas@aig.com",
            "betzaida.soto@aig.com",
            "carlos.villafaina@aig.com",
            "daniel.villafaina@aig.com",
            "elizabeth.silvamartinez@aig.com",
            "fabio.arias@aig.com",
            "mariafernanda.pinate@aig.com",
            "francisco.campos@aig.com",
            "johan.alcala@aig.com",
            "jorge.jaimes@aig.com",
            "juan.costa@aig.com",
            "julio.ortiz@aig.com",
            "leslie.alvarez@aig.com",
            "lohengrin.rossell@aig.com",
            "luzmaria.vazquezcorona@aig.com",
            "maria.delgadillo@aig.com",
            "montserrat.becerra@aig.com",
            "tania.marcial@aig.com",
            "javier.lavin@allianz.com.mx",
            "jonathan.bonilla@allianz.com.mx",
            "luis.corona@allianz.com.mx",
            "nicolas.ollivier@allianz.com.mx",
            "sergio.ghibellini@allianz.com.mx",
            "felipe.orsi@allianz.com",
            "andrea.keenan@ambest.com",
            "carlos.delatorre@ambest.com",
            "adam@ammis.london",
            "jorge.peralta@ammis.london",
            "rafael.sanchez@ammisagente.com",
            "ruth.cruz@ammis.london",
            "alejandro.cabrera@antmga.com",
            "jmina@archunderwriters.com",
            "marian.tajadura@archre.eu",
            "melissa.hergesell@archre.eu",
            "rmaldonado@archunderwriters.com",
            "ovarela@arg-group.com",
            "amonteiro@australre.com",
            "grozo@australre.com",
            "hmoreno@australre.com",
            "hbrito@australre.com",
            "mcanale@australre.com",
            "pblanco@australre.com",
            "tomas.kenney@alliedworldre.com",
            "walter.chaname@alliedworldre.com",
            "alain.villard@axaxl.com",
            "alberto.hernandezt@axa.com.mx",
            "felix.winzap@axaxl.com",
            "franciscogerardo.garcia@axa.com.mx",
            "isolt.fuentes@axa.com.mx",
            "javier.rosillo@axa.com.mx",
            "jean-pierre.portmann@axaxl.com",
            "johanna.gomez@axaxl.com",
            "lourdes.robaina@axaxl.com",
            "marilena.rodriguez@axa.com.mx",
            "miguelangel.cornejo@axa.com.mx",
            "ruben.chanona@axaxl.com",
            "veronica.garcia@axa.com.mx",
            "miguel.gonzalez@baalnak.com",
            "xavier.corona@baalnak.com",
            "david.burns@barentsre.co.uk",
            "erik.jarrin@barentsrm.com",
            "garciag@barentsre.com",
            "huno@barentsre.com",
            "kgoymer@barentsre.com",
            "george.tsang@beazley.com",
            "laura.dosal@beazley.com",
            "najib.bousakr@beazley.com",
            "stephan.vieira@beazley.com",
            "stephanny.lupera@beazley.com",
            "vicente.miranda@beazley.com",
            "dmiagro@berkleyseguros.com",
            "jaramburo@berkleylac.com",
            "jdupuy@berkleylac.com",
            "pcasanova@berkleylac.com",
            "jcalvache@brickellua.com",
            "adiaz@cargocorpuw.com",
            "csanchez@cargocorpuw.com",
            "jrodriguez@cargocorpuw.com",
            "jcm@cargocorpuw.com",
            "kvital@cargocorpuw.com",
            "mgamino@cargocorpuw.com",
            "pperalta@cargocorpuw.com",
            "sgomez@cargocorpuw.com",
            "vmora@cargocorpuw.com",
            "lcampos@ccr-re.fr",
            "ocollignon@ccr-re.fr",
            "alejandro.ferrin@chaucergroup.com",
            "april.mclaughlin@chaucergroup.com",
            "daniel.reyes@chaucerplc.com",
            "gabriel.mayorga@chaucerplc.com",
            "gustavo.guevara@chaucergroup.com",
            "itziar.gonzalez@chaucergroup.com",
            "jimena.salgado@chaucergroup.com",
            "liliana.ortiz@chaucergroup.com",
            "alfonso.barra@chubb.com",
            "carlos.batista@chubb.com",
            "carolina.munoz@chubb.com",
            "diego.gonzalez1@chubb.com",
            "fabricio.sevilla@chubb.com",
            "fernando.pizarro@chubb.com",
            "francisco.camarena@chubb.com",
            "francisco.servin@chubb.com",
            "ian.mclauchlan@chubb.com",
            "jeannette.arias@chubb.com",
            "judith.hernandez@chubb.com",
            "laura.porras@chubb.com",
            "marcos.gunn@chubb.com",
            "mariaeva.calle@chubb.com",
            "marigaby.mainero@chubb.com",
            "juan.miranda@chubb.com",
            "michelle.reategui@chubb.com",
            "patricia.garcia@chubb.com",
            "raquel.hernandez@chubb.com",
            "ricardo.montanosm@chubb.com",
            "tania.caballero@chubb.com",
            "victor.ruiz@chubb.com",
            "yadim.trujillo@chubb.com",
            "yerleen.lopez@chubb.com",
            "david.shuerch@coface.com",
            "cramirez@deltare.net",
            "dmansilla@deltare.net",
            "enicolicchia@deltareinsurancegroup.com",
            "fguzman@deltare.net",
            "mmarcano@deltare.net",
            "operdomo@deltare.net",
            "pmoreno@deltare.net",
            "yescalante@deltare.net",
            "florian.kummer@deutscherueck.de",
            "mariana.vilmondes@deutscherueck.de",
            "gabriel.buzo@dock-re.com",
            "paola.benitez@dock-re.com",
            "adriana.perez@dynamicreinsurance.com",
            "alan.martinez@dynamicreinsurance.com",
            "francisco@dynamicreinsurance.com",
            "hector.hurtado@dynamicreinsurance.com",
            "jocelyn.naranjo@dynamicreinsurance.com",
            "jose.hernandez@dynamicreinsurance.com",
            "lorena.arciniegas@dynamicreinsurance.com",
            "ariadna.garcia@echore.com",
            "sergio.perez@echore.com",
            "blopez@eurekare.com",
            "ogarcia@eurekare.com",
            "arlette.lopez@everestre.com",
            "carlos.becerra@everestre.com",
            "carlos.zepeda@everestre.com",
            "casandra.ceballos@everestre.com",
            "christian.molina@everestre.com",
            "emerson.bezerra@everestre.com",
            "enrique.matallana@everestglobal.com",
            "juan.delgado@everestre.com",
            "juliana.canon@everestre.com",
            "lesbia.azpe@everestre.com",
            "roberto.brandon@everestre.com",
            "rocio.dupuy@everestglobal.com",
            "rui.marliere@everest.com",
            "sean.berry@everestre.com",
            "yanet.gonzalez@everestre.com",
            "yrma.olivares@everestre.com",
            "andrea.olvera@genre.com",
            "cavina@genre.com",
            "campana@genre.com",
            "agata@genre.com",
            "reyes@genre.com",
            "guzman@genre.com",
            "dsuarez@global-aero.com",
            "alberto.cenoz@redkune.mx",
            "adriana.narino@hamiltongroup.com",
            "juan.melo@hamiltongroup.com",
            "pepe.marquez@hamiltongroup.com",
            "alejandra.bautista@hannover-re.com",
            "andres.patino@hannover-re.com",
            "angela.jaramillo@hannover-re.com",
            "bruna.moura@hannover-re.com",
            "bryan.urbano@hannover-re.com",
            "catalina.prada@hannover-re.com",
            "daniela.perilla@hannover-re.com",
            "daniela.vera@hannover-re.com",
            "erika.duran@hannover-re.com",
            "felipe.montero@hannover-re.com",
            "jose-daniel.bernal@hannover-re.com",
            "juan.medina@hannover-re.com",
            "luis.pulido@hannover-re.com",
            "miguel.guarin@hannover-re.com",
            "montserrat.vizcayno@hannover-re.com",
            "moris.castro-olivares@hannover-re.com",
            "nancy.triana@hannover-re.com",
            "paola.muneton@hannover-re.com",
            "roberto.castillo@hannover-re.com",
            "rodrigo.cortez@hannover-re.com",
            "stefan.krause@hannover-re.com",
            "eduardo.hernandez@mx.hdi.global",
            "erick.said@mx.hdi.global",
            "lourdes.valencia@mx.hdi.global",
            "omar.mendoza@mx.hdi.global",
            "raymundo.cruz@mx.hdi.global",
            "veronica.alanis@mx.hdi.global",
            "alain.bizet@helvetia.com",
            "andres.franco@helvetia.com",
            "danaise.abril@helvetia.com",
            "ingrid.soto@helvetia.com",
            "john.giralt@helvetia.com",
            "leonardo.morales@helvetia.com",
            "luc.grossenbacher@helvetia.ch",
            "luis.tejada@helvetia.com",
            "mariajose.cordovez@helvetia.com",
            "ana.matallana@hiscox.com",
            "christian.salcedo@hiscox.com",
            "jo.lord@hiscox.com",
            "karla.castro@hiscox.com",
            "mercedes.betancourt@hiscox.com",
            "napoleon.montes-amaya@hiscox.com",
            "tomas.sarmiento@hiscox.com",
            "adorantes@hispaniarb.com",
            "dlgonzalez@hispaniarb.com",
            "pguajardo@hispaniarb.com",
            "eottino@tmhcc.com",
            "mdonovan@hcc.com",
            "pablo.adoue@hyperseguros.com",
            "ricardo.martinez@hyperseguros.com",
            "carango@insightreinsurance.com",
            "jduque@insightreinsurance.com",
            "naguilar@insightreinsurance.com",
            "jose.ospina@interplusre.com",
            "aline.castro@irbre.com",
            "daniele.araujo@irbre.com",
            "hugo.teixeira@irbre.com",
            "luiza.souza@irbre.com",
            "marcus.machado@irbre.com",
            "marina.castro@irbre.com",
            "raul.gonzalez@irbre.com",
            "ronald.affat@irbre.com",
            "ronaldo.pinelli@irbre.com",
            "oscar@irmre.com",
            "paula@irmre.com",
            "jorge.linero@kemahcapital.com",
            "jose.rojas@kemahcapital.com",
            "mario.montero@kemahcapital.com",
            "andre.myung@koreanre.co.kr",
            "sonrisa@koreanre.co.kr",
            "franciscoforero@larandsons.com",
            "hectormartinez@larandsons.com",
            "lucyraymond@larandsons.com",
            "adel.satizabal@libertymutual.com",
            "adrian.hernandez@libertymutual.com",
            "aldo.paino@libertyiu.com",
            "arturo.posada@libertymutual.com",
            "conrado.sterling@libertymutual.com",
            "deisi.hernandez@libertymutual.com",
            "diana.angarita@libertymutual.com",
            "eduardo.sanchez@libertymutual.com",
            "fabian.ospina@libertyiu.com",
            "gabriela.palacios@libertyiu.com",
            "humberto.pozo@libertyiu.com",
            "juancarlos.salcedo@libertyiu.com",
            "juan.lopez@libertymutual.com",
            "michael.robertson@libertymutual.com",
            "ronald.bolanos@libertyiu.com",
            "rosa.floresjuarez@libertyglobalgroup.com",
            "alvaro.salamanca@libertymutual.com",
            "carolina.carmona@libertymutual.com",
            "douglas.sakamoto@libertymutual.com",
            "javier.guardia@libertymutual.com",
            "livia.barreira@libertymutual.com",
            "luis.paternina@libertymutual.com",
            "luisa.hoyos@libertymutual.com",
            "mauricio.rodriguez@libertyglobalgroup.com",
            "ximena.rodriguez@libertyglobalgroup.com",
            "jeanchristophe.garaix@libertysyndicates.fr",
            "daniel.revilla@lloyds.com",
            "yelhis.hernandez@lloyds.com",
            "mariaalvarado@mapfre.com",
            "bernaga@mapfre.com",
            "cvertti@mapfre.com",
            "dinesto@mapfre.com",
            "abarcaa@mapfre.com",
            "eduardolopez@mapfre.com",
            "agarciam@mapfre.com",
            "bcmario@mapfre.com",
            "paguti1@mapfre.com",
            "gabriela.ramirez@mapfre.com",
            "raquel.dominguez@mapfre.com",
            "danieldesousa@mercantilre.com",
            "rquintero@mercantilre.com",
            "ariana.ferreruela@msreinsurance.com",
            "edward.herrera@msreinsurance.com",
            " jovan.velasquez@msreinsurance.com",
            "louis.desegonzac@msamlin.com",
            "lucas.castagnino@msreinsurance.com",
            "mariana.mendez@msamlin.com",
            "santiago.deluchi@mreinsurance.com",
            "afeldhaus@munichre.com",
            "angonzalez@munichre.com",
            "crendon@munichre.com",
            "cbartsch@munichre.com",
            "damedina@munichre.com",
            "dortegamayorga@munichre.com",
            "dkasanova@munichre.com",
            "emitre@munichre.com",
            "freyes@munichre.com",
            "mmendoza@munichre.com",
            "focampo@munichre.com",
            "ggarciacano@munichre.com",
            "gblanco@munichre.com",
            "jromero@munichre.com",
            "jsanchez@munichre.com",
            "jayalde@munichre.com",
            "jugonzalez@munichre.com",
            "jsegelbacher@munichre.com",
            "kcruz@munichre.com",
            "lsolis@munichre.com",
            "lmiranda@munichre.com",
            "mneumeier@munichre.com",
            "mkueckemanns@munichre.com",
            "mgonzalez@munichre.com",
            " rpaul@munichre.com",
            "rvargas@munichre.com",
            "rgalicia@munichre.com",
            "rschmid@munichre.com",
            "ssantiago@munichre.com",
            "francois.cardiergonzalez@thehartford.com",
            "antonio.price@thehartford.com",
            "ccampos@navg.com",
            "edward.benavides@thehartford.com",
            "efrain.sora@thehartford.com",
            "ivan.vega@thehartford.com",
            "laura.jensen@thehartford.com",
            "luis.jaramillo@thehartford.com",
            "massiel.verasmelendez@thehartford.com",
            "rafael.derett@thehartford.com",
            "rodrigo.suarez@thehartford.com",
            "dllamas@newlinegroup.com",
            "gmendoza@newlinegroup.com",
            "srueda@newlinegroup.com",
            "areyes@oceanre.biz",
            "cchamorro@oceanre.biz",
            "egonzalez@oceanre.biz",
            "geslava@oceanre.biz",
            "iurena@oceanre.biz",
            "aurena@oceanre.biz",
            "jrajoy@oceanre.biz",
            "krogers@oceanre.biz",
            "ysanchez@oceanre.biz",
            "amontoya@odysseyre.com",
            "alejandrodominguez@odysseyre.com",
            "aramirez@odysseyre.com",
            "azuniga@odysseyre.com",
            "cblanco@odysseyre.com",
            "amarcano@odysseyre.com",
            "osanchez@odysseyre.com",
            " jdetomas@odysseyre.com",
            "mnunez@odysseyre.com",
            "nguerra@odysseyre.com",
            "osanchez@odysseyre.com",
            "pmallier@odysseyre.com",
            "rguzman@odysseyre.com",
            "rmartinez@odysseyre.com",
            "vgomez@odysseyre.com",
            "yloyola@odysseyre.com",
            "maya.valencia@partnerre.com",
            "miuriell.sandoval@partnerre.com",
            "pedro.reyes@partnerre.com",
            "rafael.calzadilla@partnerre.com",
            "rodrigo.silva@partnerre.com",
            "sabah.diffalah@partnerre.com",
            "sariza.chavez@partnerre.com",
            "victor.osuna@partnerre.com",
            "enrique.morales@probitas1492.com",
            "mauricio.morales@probitas1492.com",
            "roberto.gomez@probitas1492.com",
            "alfonso.demares@qbe.com",
            "ademares@qbeim.com",
            "blabrador@qbeim.com",
            "creal@qbeim.com",
            "christian.hofmann@qbere.com",
            "david.bernaldelgado@qbere.com",
            "frojas@qbeim.com",
            "fbunge@qbeim.com",
            "gavan.manifold@qbere.com",
            "guido.wolman@qbere.com",
            "john.garcia@ie.qbe.com",
            "jdmejia@qbeim.com",
            "mcruz@qbeim.com",
            "mchinea@qbeim.com",
            "nicholas.wise@ie.qbe.com",
            "paula.mackenzie@uk.qbe.com",
            "mtueller@qregroup.com",
            "alfonso.perez@ruv.de",
            "ina.schmidt@ruv.de",
            "katharina.cronen@ruv.de",
            "leon.rave@ruv.de",
            "luis.salcedo@ruv.de",
            "bpj@rainmaker-i.com",
            "caa@rainmakergroup.com",
            "cll@rainmakergroup.com",
            "fog@rainmakergroup.com",
            "gho@rainmakergroup.com",
            "gg@rainmakergroup.com",
            "me@rainmakergroup.com",
            "vmg@rainmakergroup.com",
            "oeer@ecuare.com",
            "gutierrezaa@icloud.com",
            "asalazarp@patriare.com.mx",
            "adservin@patriare.com.mx",
            "agardunoj@patriare.com.mx",
            "amcorralv@patriare.com.mx",
            "amarquez@patriare.com.mx",
            "amfloress@patriare.com.mx",
            "acuenca@patriare.com.mx",
            "bdiaz@patriare.com.mx",
            "bvillaj@patriare.com.mx",
            "bvillaj@patriare.com.mx",
            "decuevasr@patriare.com.mx",
            "dvargasc@patriare.com.mx",
            "dygarcias@patriare.com.mx",
            "dbustamantep@patriare.com.mx",
            "dmcastrom@patriare.com.mx",
            "ebetancourt@patriare.com.mx",
            "exhemalce@patriare.com.mx",
            "elopezg@patriare.com.mx",
            "enavarrete@patriare.com.mx",
            "emartinezo@patriare.com.mx",
            "fmartinez@patriare.com.mx",
            "gzarraga@patriare.com.mx",
            "ggalicia@patriare.com.mx",
            "grodriguez@patriare.com.mx",
            "iestrada@patriare.com.mx",
            "abustamante@patriare.com.mx",
            "ilopez@patriare.com.mx",
            "isrosaso@patriare.com.mx",
            "jreyes@patriare.com.mx",
            "jnucamendi@patriare.com.mx",
            "jrvelazquezc@patriare.com.mx",
            "jajimenezc@patriare.com.mx",
            "lruiz@patriare.com.mx",
            "jcrosalesm@patriare.com.mx",
            "jjsagredol@patriare.com.mx",
            "jrios@patriare.com.mx",
            "jccorzos@patriare.com.mx",
            "kmcervantesv@patriare.com.mx",
            "lxguzmanh@patriare.com.mx",
            "lmromerop@patriare.com.mx",
            "mcamachor@patriare.com.mx",
            "mmnunezr@patriare.com.mx",
            "mescobedo@patriare.com.mx",
            "micruzs@patriare.com.mx",
            "mngarciap@patriare.com.mx",
            "nmontoyar@patriare.com.mx",
            "oramosh@patriare.com.mx",
            "onolasco@patriare.com.mx",
            "pchavez@patriare.com.mx",
            "rtlaseca@patriare.com.mx",
            "rmendoza@patriare.com.mx",
            "rmunozr@patriare.com.mx",
            "rhernandeza@patriare.com.mx",
            "ssguzmanh@patriare.com.mx",
            "vimorenog@patriare.com.mx",
            "vrobledo@patriare.com.mx",
            "xdgarcias@patriare.com.mx",
            "alejandro.salamanca@renre.com",
            "andres.pardo@renre.com",
            "gaby.briceno@renre.com",
            "martin.gonzalez@renre.com",
            "daniel.zurita@rgare.com ",
            "eduardo.lara@rgare.com",
            "gledesma@rgare.com",
            "jespinola@rgare.com",
            "lgarcia@rgare.com",
            "msuarez@rgare.com ",
            "marcos.prada@rokstoneum.com",
            "alomeli@scor.com",
            "acorrealgaviria@scor.com",
            "dserrato@scor.com",
            "dsanabria@scor.com",
            "fdiaz@scor.com",
            "fmajos@scor.com",
            "gmartinezfentanez@scor.com",
            "iforero@scor.com",
            "jgrieve@scor.com",
            "jmalagon@scor.com",
            "jselsted@scor.com",
            "jblancoospina@scor.com",
            "kfujita@scor.com",
            "mcarrillo@scor.com",
            "mbarrera@scor.com",
            "mvelasquez@scor.com",
            "vbergamaschi@scor.com",
            "vrubio@scor.com",
            "vmstewens@yahoo.com.mx",
            "adowney@solisre.com",
            "clefferdink@solisre.com",
            "jcroa@solisre.com",
            "david.molano@slunderwriters.com",
            "diana.castiblanco@slunderwriters.com",
            "joseomar.rodriguez@slunderwriters.com",
            "yesid.rodriguez@slunderwriters.com",
            "yolanda.achury@slunderwriters.com",
            "alvaro.patino.tellez@starrcompanies.com",
            "doug.bell@starrcompanies.com",
            "john.torres@starrcompanies.com",
            "jose.torres@starrcompanies.com",
            "kenneth.haddock@starrcompanies.com",
            "kyle.sparks@starrcompanies.com",
            "maggie.espinoza@starrcompanies.com",
            "marco.anaya@starrcompanies.com",
            "vanessa.flores@starrcompanies.com",
            "yessenia.fajardo@starrcompanies.com",
            "mike.hernandez@sbrickell.com",
            "adriana_valdes@swissre.com",
            "alvaro_costa@swissre.com",
            "ana_velazquez@swisssre.com",
            "anavictoria_mejia@swissre.com",
            "angeles_aguilar@swissre.com",
            "angelinne_linares@swissre.com",
            "armando_venegas@swissre.com",
            "armando_zazueta@swissre.com",
            "cari_olivieri@swissre.com",
            "diana_barcenas@swissre.com",
            "eduardo_herrera@swissre.com",
            "eduardo_machuca@swissre.com",
            "erika_schoch@swissre.com",
            "francisco_diaz@swissre.com",
            "gabrielatamara_luna@swissre.com",
            "guadalupe_sanchez@swissre.com",
            "guillermo_hernandez@swissre.com",
            "gustavo_campos@swissre.com",
            "hannia_yohalicabrerarodriguez@swissre.com",
            "ignacio_lucario@swissre.com",
            "isabel_diaz@swissre.com",
            "israel_paredes@swissre.com",
            "itzel_valdez@swissre.com",
            "izabella_ohata@swissre.com",
            "jacquelineivette_torres@swissre.com",
            "jacqueline_navarrete@swissre.com",
            "jens_mehlhorn@swissre.com",
            "jorge_ballinas@swissre.com",
            "jorge_garduno@swissre.com",
            "jorge_guereca@swissre.com",
            "joseantonio_andrade@swissre.com",
            "jose_flores@swissre.com",
            "karen_galvan@swissre.com",
            "karina_ruiz@swissre.com",
            "lidia_rafael@swissre.com",
            "luciano_carmona@swissre.com",
            "luis_balestrini@swissre.com",
            "luis_meneses@swissre.com",
            "mariafernanda_alonso@swissre.com",
            "marcela_rincon@swissre.com",
            "marco_ortiz@swissre.com",
            "maricruz_pinedagaona@swissre.com",
            "maritza_cano@swissre.com",
            "mauricio_trulin@swissre.com",
            "milton_gutierrez@swissre.com",
            "miriam_avila@swissre.com",
            "monserrat_arguelles@swissre.com",
            "myriam_andonie@swissre.com",
            "nathaliaguadalupe_gonzalezoliva@swissre.com",
            "nikhil_davictorialobo@swissre.com",
            "paola_osorio@swissre.com",
            "patricia_quintero@swissre.com",
            "rafael_delgado@swissre.com",
            "richard_schneider@swissre.com",
            "rodrigo_leon@swissre.com",
            "rodrigo_mellado@swissre.com",
            "rosa_leon@swissre.com",
            "rosa_moran@swissre.com",
            "rubem_hofliger@swissre.com",
            "sally_valencia@swissre.com",
            "sara_vargas@swissre.com",
            "sergio_bunin@swissre.com",
            "tanya_canty@swissre.com",
            "valentina_garcia@swissre.com",
            "wendyalejandra_angelhernandez@swissre.com",
            "yesid_sarmiento@swissre.com",
            "daniel_gomez@swissre.com",
            "isabelle_heuder@swissre.com",
            "gabriela_garcia@swissre.com",
            "afalcon@tamesisreins.com",
            "jcoronado@tamesisreins.com",
            "mgiovane@tamesisreins.com",
            "jaguilar@redbridge.cc",
            "jmrojore@gmail.com",
            "maguilar@totallre.com",
            "pcenturion@transre.com",
            "aeisenberg@transre.com",
            "avalle@transre.com",
            "eporcel@transre.com",
            "ielizeu@transre.com",
            "jvijil@transre.com",
            "jbeltran@transre.com",
            "mtrovato@transre.com",
            "mgomez@transre.com",
            "mmarquez@transre.com",
            "mkelly@transre.com",
            "mpinto@transre.com",
            "nocampo@transre.com",
            "smunoz@transre.com",
            "snarciso@transre.com",
            "vsotomayor@transre.com",
            "dolores.medina@usaig.com",
            "kyle.anderson@usaig.com",
            "robert.houck@usaig.com",
            "andrew.umphress@validusre.com",
            "bill.fischer@validusamericas.com",
            "luis.sonville@talbotuw.com",
            "rafael.saer@validusre.com",
            "angelica.hernandez@xsglobal.com",
            "gabriela.esquivel@xsglobal.com",
            "gabriela.martinez@xsglobal.com",
            "hermis.gonzalez@xsglobal.com",
            "natalia.valdez@xsglobal.com",
            "orlando.garcia@xsglobal.com",
            "paul.felfle@xsglobal.com",
            "pedro.farinas@xs-global.net",
            "rodrigo.lopez@xsglobal.com",
            "jorge.campa@xsglobal.com",
            "afrutos@xs-global.net",
            "aranalletta@xs-global.net",
            "anthony.willsher@xsglobal.com",
            "camilo.escobar@xsglobal.com",
            "gesquivel@xs-global.net",
            "gerardo.jacobo@xsglobal.com",
            "german.marconi@xsglobal.com",
            "juan.martinez@xsglobal.com",
            "nestor.rodriguez@xsglobal.com",
            "ryglesias@xs-global.net",
            "sebastian.schlossberg@xsglobal.com",
            "arantxa.jimenez@mx.zurich.com",
            "bernardo.juarez@zurich.com",
            "diana.1.cano@mx.zurich.com",
            "luis.lobera@mx.zurich.com",
            "jose.salgado5@mx.zurich.com",
            "lucia.delcid@mx.zurich.com",
            "luis.lujano@mx.zurich.com",
            "raul.vidal@mx.zurich.com",
            "roxana.winkler@mx.zurich.com",
            "crojas@elasegurador.com.mx",
            "carojas@elasegurador.com.mx",
            "genuario@elasegurador.com.mx",
            "rmartinez@elasegurador.com.mx",
            "xanath@elasegurador.com.mx",
            "agustin.defreitas@gmail.com",
            "alejandro.vazquez@som.us",
            "israel.zurita@som.us",
            "luis.linares@som.us",
            "maria.ferrari@som.us",
            "mauricio.rodriguez@som.us",
            "camilo.samper@reasesoresltda.com.co",
            "luis.porras@reasesoresltda.com.co",
            "victor.ribon@gmail.com",
            "oxor11@gmail.com",
            "afloresm@cipe.com.mx",
            "dogmeyran1@gmail.com",
            "carlos.martinez@safetyfuture.com.mx",
            "eligioserna@yahoo.com",
            "erobleda@yahoo.com.mx",
            "dorcom3@hotmail.com",
            "frobleda@me.com",
            "cmtzmora@hotmail.com",
            "alexander.riveros@axiscapital.com",
            "carlos.huesca@bmsgroup.com",
            "cynthia.gallegos@bmsgroup.com",
            "diana.martinez@bmsgroup.com",
            "elvia.rodriguez@bmsgroup.com",
            "felipe.reyes@bmsgroup.com",
            "gabriel.inesta@bmsgroup.com",
            "jimena.morenoromero@bmsgroup.com",
            "manolo.camacho@bmsgroup.com",
            "mario.andrade@bmsgroup.com",
            "mario.rochell@bmsgroup.com",
            "emanuel.rochell@bmsgroup.com",
            "martha.vargas@bmsgroup.com",
            "martin.perea@bmsgroup.com",
            "mitzy.lopez@bmsgroup.com",
            "oscar.chavez@bmsgroup.com",
            "paulina.fernandez@bmsgroup.com",
            "roberto.alvarado@bmsgroup.com",
            "genuario@elasegurador.com.mx",
            "jgomez@insightreinsurance.com",
            "miguel.hernandez@libertymutual.com",
            "santiago.deluchi@msreinsurance.com",
            "jarellano@munichre.com",
            "alavantea@patriare.com.mx",
            "emartinezo@patriare.com.mx",
            "gabriela_martinez@swissre.com",
            "tanya_cantu@swissre.com",
            "eroca@totallre.com",
            "jairo.mejia@3c.com.co",
            "drouse@aegislondon.co.uk",
            "david.colmenaras@allianz.com",
            "rafael.luna@allianz.com",
            "laura.narro@amwins.com",
            "bfreire@australre.com",
            "esilva@australre.com",
            "hmoreno@australre.com",
            "pblanco@australre.com",
            "george.tsang@beazley.com",
            "laura.dosal@beazley.com",
            "najib.bousakr@beazley.com",
            "stephan.vieira@beazley.com",
            "stephanny.lupera@beazley.com",
            "vicente.miranda@beazley.com",
            "emily.weighton@bmsgroup.com",
            "sconsulting.re@gmail.com",
            "juan.gomez@bmsgroup.com",
            "aescoto@cargocorpuw.com",
            "ernesto.hernandez@chubb.com",
            "luis.mata@chubb.com",
            "tania.sanchez@chubb.com",
            "david.vargas@dynamicreinsurance.com",
            "ebetancourt@dynamicreinsurance.com",
            "eric.baeza@dynamicreinsurance.com",
            "ruben.hoyos@dynamicreinsurance.com",
            "valeria@dynamicreinsurance.com",
            "martin.beltran@hyperseguros.com",
            "joaquinserrano@latinoins.com",
            "jfserrano@latinoins.com",
            "apons@munichre.com",
            "larregui@munichre.com",
            "marodriguez@munichre.com",
            "gabriel.anguiano@priceforbes.com",
            "fabiola.encarnacion@rgare.com",
            "abril.delcastillo@summare.com.mx>",
            "alejandro.calderon@summare.com.mx>",
            "angelica.estrada@summare.com.mx>",
            "araceli.bautista@summare.com.mx>",
            "claudia.aragon@summare.com.mx>",
            "elizabeth.arredondo@summare.com.mx>",
            "erika.aguirre@summare.com.mx>",
            "erika.vigil@summare.com.mx>",
            "fredy.marino@summare.com.mx>",
            "jacklyn.serrano@summare.com.mx>",
            "javier.gallo@summare.com.mx>",
            "jessica.gutierrez@summare.com.mx>",
            "luis.gutierrez@summare.com.mx>",
            "mariana.bastida@summare.com.mx>",
            "mario.martinez@summare.com.mx>",
            "mario.beltran@summare.com.mx>",
            "maritza.navarro@summare.com.mx>",
            "pablo.salinas@summare.com.mx>",
            "pablo.cervantes@summare.com.mx>",
            "patricia.lara@summare.com.mx>",
            "rafael.picazo@summare.com.mx>",
            "yolanda.vazquez@summare.com.mx>",
            "gsanchezlx@gmail.com",
            "abigail.quijada@tbsmexico.com.mx",
            "alejandro.riquelme@tbsmexico.com.mx",
            "alejandro.serrano@tbsmexico.com.mx",
            "arturo.pastrana@afirme.com",
            "cecilia.sanchez@tbsmexico.com.mx",
            "daniel.yanez@tbsmexico.com.mx",
            "ericka.melo@tbsmexico.com.mx",
            "fernando.aguilera@tbsmexico.com.mx",
            "humberto.avalos@tbsmexico.com.mx",
            "ivan.estrada@tbsmexico.com.mx",
            "jorge.jockens@tbsmexico.com.mx",
            "josecarlos.blanco@tbsmexico.com.mx",
            "juanmanuel.name@tbsmexico.com.mx",
            "manolo.guillen@tbsmexico.com.mx",
            "mauricio.caire@tbsmexico.com.mx",
            "ramon.cortez@tbsmexico.com.mx",
            "ricardo.salgado@tbsmexico.com.mx",
            "alejandro.solorzano@xsglobal.com",
            "natalia.martinez@xsglobal.com",
            "agm@rainmakergroup.com",
            "david.colmenares@allianz.com",
            "rui.marliere@everestre.com",
            "felipe.campana@genre.com",
            "lrayes@genre.com",
            "erika.aguirre@summare.com.mx>",
            "josue@kayint-amea.com",
            "cardona@kayint-amea.com",
            "agm@rainmakergroup.com",
            "csierra@munichre.com",
            /*Somus Internos*/
            "alan.castillo@som.us",
            "eduardo.neria@som.us",
            "ivan.chavez@som.us",
            "diana.silva@som.us",
            "enrique.martinez@som.us",
            "luis.salinas@som.us",
            "adriana.gomora@som.us",
            "daniel.hernandez@som.us",
            "aiknara.lopez@som.us",
            "rebeca.ramirez@som.us",
            "patricia.flores@som.us",
            "horacio.ordonez@som.us",
            "felipe.castillo@som.us",
            "oscar.arellano@som.us",
            "yazmin.azpeitia@som.us",
            "lizeth.perez@som.us",
            "brayan.andrade@som.us",
            "mariana.luna@som.us",
            "jacqueline.ramirez@som.us",
            "berenice.cervantes@som.us",
            "melissa.yanez@som.us",
            "veronica.tapia@som.us",
            "hugo.yllescas@som.us",
            "elias.sevilla@som.us",
            "viridiana.balderas@som.us",
            "francisco.martinez@som.us",
            "martha.beltran@som.us",
            "raul.castillo@som.us",
            "guadalupe.camacho@som.us",
            "ricardo.martinez@som.us",
            "jenny.maldonado@som.us",
            "eugenia.cruz@som.us",
            "letymej13@gmail.com",
            "gabriela.poncedeleon@axa.com.mx",
            "francely.vicens@redlineuw.com",
            "amir.loske@allianz.com.mx",
            "paola.nava@chubb.com",
            "astrid_uribe@swissre.com",
            "andy@safehub.io",
            "roberto_gomez@swissre.com",
            "jimena_reyes@swissre.com"
        };
    }
}
