using System;
using System.Collections.Generic;
using System.Text;

namespace PruebasScanner.Models
{
    class EmpresasCorto
    {
        public Dictionary<string, string> empresas = new Dictionary<string, string>() {
            {"ACTIVE CAPITAL REINSURACE", "ACTIVE CAPITAL"},
            {"ACTIVE RE", "ACTIVE RE"},
            {"AGROASEMEX", "AGROASEMEX"},
            {"AIG", "AIG"},
            {"AIG - FAC DESK MIAMI", "AIG"},
            {"AIG SEGUROS MÉXICO", "AIG"},
            {"AIG SEGUROS MEXICO, S.A.", "AIG"},
            {"ALLIANZ", "ALLIANZ"},
            {"AM BEST", "AM BEST"},
            {"AMMIS RISK SOLUTIONS LTD.", "AMMIS RISK"},
            {"AMWINS GLOBAL RISKS", "AMWINS GLOBAL"},
            {"AUSTRAL RE", "AUSTRAL RE"},
            {"AUSTRAL TE", "AUSTRAL RE"},
            {"AXA", "AXA"},
            {"BAAL NAK REINSURANCE CONSULTANTS, LLC", "BAAL NAK"},
            {"BEAZLEY", "BEAZLEY"},
            {"BERKLEY INSURANCE COMPANY", "BERKLEY"},
            {"BMS", "BMS"},
            {"BMS GROUP", "BMS"},
            {"BMS GROUP - LONDON", "BMS"},
            {"BMS LATIN AMERICA & CARIBBEAN", "BMS"},
            {"BMS RE", "BMS"},
            {"BMS RE MEXICO", "BMS"},
            {"BMS RE MÉXICO", "BMS"},
            {"BMS RE MÉXICO INTERMEDIARIO DE REASEGURO", "BMS"},
            {"BMS RE MÉXICO INTERMEDIARIO DE REASEGURO SA DE CV", "BMS"},
            {"BRICKELL UNDERWRITING AGENCY", "BUA"},
            {"BUA - BRICKELL UNDERWRITING AGENCY", "BUA"},
            {"CARGOCORP UNDERWRITERS", "CARGOCORP"},
            {"CARGOCORP UW", "CARGOCORP"},
            {"CARGOCORPUW", "CARGOCORP"},
            {"CHAUCER", "CHAUCER"},
            {"CHUBB", "CHUBB"},
            {"CHUBB FAC RE (MIAMI)", "CHUBB"},
            {"CHUBB SEGUROS", "CHUBB"},
            {"CHUBB SEGUROS MEXICO", "CHUBB"},
            {"CHUBB SEGUROS MÉXICO", "CHUBB"},
            {"DOCK RE", "DOCK RE"},
            {"DYNAMIC RE", "DYNAMIC RE"},
            {"DYNAMIC REINSURANCE", "DYNAMIC RE"},
            {"EL ASEGURADOR", "EL ASEGURADOR"},
            {"EUREKA RE", "EUREKA RE"},
            {"EVEREST RE", "EVEREST RE"},
            {"EVEREST REINSURANCE  COMPANY", "EVEREST RE"},
            {"GENERAL REINSURANCE", "GENERAL REINSURRANCE"},
            {"HANNOVER RE", "HANNOVEER RE"},
            {"HDI GLOBAL", "HDI GLOBAL"},
            {"HDI GLOBAL SEGUROS", "HDI GLOBAL"},
            {"HELVETIA", "HELVETIA LATIN"},
            {"HELVETIA LATIN AMERICA LLC", "HELVETIA LATIN"},
            {"HISPANIA", "HISPANIA RISK"},
            {"HISPANIA RISK BROKER", "HISPANIA RISK"},
            {"HYPERSEGUROS", "HYPERSEGUROS"},
            {"INDEPENDIENTE", "INDEPENDIENTE"},
            {"INTERPLUS RE", "INTERPLUS RE"},
            {"LATINOINSURANCE", "LATINOINSURANCE"},
            {"LIBERTY", "LIBERTY MUTUAL"},
            {"LIBERTY MUTUAL", "LIBERTY MUTUAL"},
            {"LIBERTY MUTUAL - LSM", "LIBERTY MUTUAL"},
            {"LIBERTY MUTUAL INSURANCE COMPANY", "LIBERTY MUTUAL"},
            {"LIBERTY MUTUAL RE", "LIBERTY MUTUAL"},
            {"LLOYDS", "LLOYDS"},
            {"MAPFRE RE", "MAPFRE RE"},
            {"MAPFRE RE COMPAÑIA DE REASEGUROS SA", "MAPFRE RE"},
            {"MAPFRE RE COMPAÑÍA DE REASEGUROS, S.A.", "MAPFRE RE"},
            {"MARTÍNEZ MORA", "MARTÍNEZ  MORA"},
            {"MUNICH RE", "MUNICH RE"},
            {"MUNICH RE MEXICO", "MUNICH RE"},
            {"NAVIGATORS", "NAVIGATORS"},
            {"NAVIGATORS INSURANCE COMPANY", "NAVIGATORS INSURANCE"},
            {"NEWLINE GROUP", "NEWLINE GROUP"},
            {"NEWLINE SYNDICATE 1218", "NEWLINE 1218"},
            {"OCEAN", "OCEAN INTERNATIONAL"},
            {"OCEAN INTERNATIONAL REINSURANCE COMPANY", "OCEAN INTERNATIONAL"},
            {"OCEAN RE", "OCEAN RE"},
            {"ODYSSEY", "ODYSSEY LATIN"},
            {"ODYSSEY RE", "ODYSSEY RE"},
            {"ODYSSEY REINSURANCE", "ODYSSEY RE"},
            {"ODYSSEY REINSURANCE COMPANY", "ODYSSEY RE"},
            {"ODYSSEYRE", "ODYSSEY RE"},
            {"PARTNER RE", "PARTNER RE"},
            {"PARTNERRE", "PARTNER RE"},
            {"PATRIA RE", "PARTNER RE"},
            {"PATRIARE", "PARTNER RE"},
            {"PEÑA VERDE", "PEÑA VERDE"},
            {"PERIÓDICO EL ASEGURADOR", "EL ASEGURADOR"},
            {"PERSONAL", "PERSONAL"},
            {"PROBITAS 1492", "PROBITAS 1492"},
            {"PRUEBA", "PRUEBA"},
            {"QBE", "QBE"},
            {"RAINMAKER GROUP", "RAINMAKER GGROUP"},
            {"REA", "REA LATIN"},
            {"REASEGURADORA PATRIA", "REASEGURADORA PATRIA"},
            {"REASEGURADORA PATRIA, S. A.", "REASEGURADORA PATRIA"},
            {"REASEGURADORA PATRIA, S.A.", "REASEGURADORA PATRIA"},
            {"REASESORES SA", "REASESORES SA"},
            {"REDLINE/CHAUCER", "REDLINE CHAUCER"},
            {"RISC", "RISC"},
            {"ROKSTONE UNDERWRITING MANAGERS LLC", "ROKSTONE"},
            {"SAFEHUB", "SAFEHUB"},
            {"SCOR", "SCOR"},
            {"SCOR REINSURANCE CO.", "SCOR REINSURANCE"},
            {"SCOR REINSURANCE COMPANY", "SCOR REINSURANCE"},
            {"SOM.US", "SOM US MÉXICO"},
            {"SOM.US ECUADOR C. A.", "SOM US ECUADOR"},
            {"SOM.US INTE", "SOM US MÉXICO"},
            {"SOM.US INTERMEDIARIO DE REASEGURO", "SOM US MÉXICO"},
            {"SOM.US INTERMEDIARIO DE REASEGURO S.A. DE C.V.", "SOM US MÉXICO"},
            {"SOM.US INTERMEDIARIO DE REASEGURO SA DE CV", "SOM US MÉXICO"},
            {"SOM.US INTERMEDIARIO DE REASEGURO, S.A.", "SOM US MÉXICO"},
            {"SOM.US INTERMEDIARIO DE REASEGURO, S.A. DE C.V.", "SOM US MÉXICO"},
            {"SOM.US INTERMEDIARIOS DE REASEGURO", "SOM US MÉXICO"},
            {"SOM.US MÉXICO", "SOM US MÉXICO"},
            {"SOM.US, INTERMEDIARIO DE REASEGURO S.A. DE C.V.", "SOM US MÉXICO"},
            {"SOM.US, INTERMEDIARIO DE REASEGURO, S.A. DE C.V", "SOM US MÉXICO"},
            {"SOMUS", "SOM US MÉXICO"},
            {"SOMUS INTERMEDIARIO DE REASEGURO", "SOM US MÉXICO"},
            {"SOMUS INTERMEDIARIO DE REASEGUROS", "SOM US MÉXICO"},
            {"SRCS", "SRCS"},
            {"STARR COMPANIES", "STARR COMPANIES"},
            {"STRADA CONSULTING", "STRADA CONSULLTING"},
            {"SUMMA", "SUMMA"},
            {"SUMMA INTERMEDIARIO DE REASEGURO", "SUMMA"},
            {"SUMMA INTERMEDIARIO DE REASEGURO, S.A.P.I DE C.V.", "SUMMA"},
            {"SUMMA INTERMEDIARIO SA DE CV", "SUMMA"},
            {"SWISS RE", "SWISS RE"},
            {"SWISS RE AMERICA CORPORATION", "SWISS RE"},
            {"SWISS RE CORPORATE SOLUTIONS", "SWISS RE"},
            {"SWISS RE CORSO", "SWISS RE"},
            {"SWISS RE MEXICO", "SWISS RE"},
            {"SWISS RE MEXICO SERVICIOS, S. DE R.L. DE C.V.", "SWISS RE"},
            {"SWISS REINSURANCE AMERICA CORPORATION", "SWISS RE"},
            {"SWISSRE", "SWISS RE"},
            {"TAMESIS", "TAMESIS"},
            {"TBS", "TBS"},
            {"TBS INTERMEDIARIO DE REASEGURO", "TBS"},
            {"THE BROKER SERVICES (TBS)", "TBS"},
            {"THE HARTFORD", "THE HARTTFORD"},
            {"TOTALL-RE", "TOTALL RE"},
            {"TRANS RE", "TRANS RE"},
            {"TRANSRE", "TRANS RE"},
            {"XS GLOBAL", "XS GLOBAL"},
            {"XSGLOBAL", "XS GLOBAL"},
            {"ZURICH", "ZURICH"},
            {"ZURICH ASEGURADORA MEXICANA", "ZURICH"},
            {"ZURICH ASEGURADORA MEXICANA, SA DE CV", "ZURICH"},
            {"ZURICH ASEGURODRA MEXIACANA", "ZURICH"},
            {"ZURICH ASSEGURADORA MEXICANA SA DE CV", "ZURICH"},
            {"ZURICH MEXICO", "ZURICH"}
        };
    }
}
